# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import time_series_forecast_pb2 as time__series__forecast__pb2


class ForecastStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.forecast = channel.unary_unary(
        '/Forecast/forecast',
        request_serializer=time__series__forecast__pb2.Input.SerializeToString,
        response_deserializer=time__series__forecast__pb2.Output.FromString,
        )


class ForecastServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def forecast(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ForecastServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'forecast': grpc.unary_unary_rpc_method_handler(
          servicer.forecast,
          request_deserializer=time__series__forecast__pb2.Input.FromString,
          response_serializer=time__series__forecast__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Forecast', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
